### PR TITLE
fix(ui): user table width in modal

### LINKED ISSUE #185: Ongoing, Terminated 에서 유저테이블 width 설정 안됨
image
image

### PR DESCRIPTION
**Pull request by babycroc**
Resolves #185 

투표 대상 옆의 숫자도 수정되게 했엉요

### CODE REVIEW

**Comment by babycroc** [comment]
image

**Comment by babycroc** [comment]
Resolves #169

**Comment by babycroc** [comment]
Resolves #188

**Comment by babycroc** [comment]
Resolves #187

**Review by kjy2844 — APPROVED** [review]

**Pull request merged**
